engines:
  fixme:
    enabled: true
  checkstyle:
    enabled: true
    checks:
      com.puppycrawl.tools.checkstyle.checks.blocks.NeedBracesCheck:
        enabled: false
    channel: "beta"
  pmd:
    enabled: true
    channel: "beta"
ratings:
  paths:
  - "**.java"
exclude_paths:
- "**/test/**/*"