language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.3
    - android-24
    - extra-android-m2repository
before_install:
 - chmod +x gradlew
script: ./gradlew jacocoTestReleaseUnitTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
webhooks:
    urls:
      - https://webhooks.gitter.im/e/578f10c3a2c0e9cc4a97
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always


